services:
  node:
    container_name: qn-backend-node
    image: node:20-alpine3.20
    working_dir: /app
    command: tail -f /dev/null
    ports:
      - 3030:3030
    volumes:
      - .:/app

  database:
    image: mongo:latest
    container_name: questnutri-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=QuestNutriDB
      - DB_CONNECTION_URI=mongodb://root:root@localhost:27017/QuestNutriDB?authSource=admin
    volumes:
      - ./mount-test:/tmp/mount-test
    ports:
      - "27017:27017"

  test:
    image: questnutri/backend:1.1-withdb
    container_name: test
    ports: 
      - 45450:45450
    environment:
      - PORT=45450

    # volumes:
    #   - questnutri-volume:/data/db
    #   - questnutri-volume:/data/dump
    # command: >
    #   bash -c "
    #     mongod --bind_ip 0.0.0.0 --fork --logpath /var/log/mongod.log &&
    #     sleep 5 &&
    #     mongodump --uri='mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}${DB_CONNECTION_URI}' --out=/dump &&
    #     mongorestore --uri='mongodb://localhost:27017' /dump &&
    #     tail -f /dev/null
    #   "
    # restart: always

# volumes:
#   questnutri-volume:
#     driver: local